# Generated by Django 5.1.3 on 2025-01-01 14:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal ID', unique=True, verbose_name='Internal ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the object is active or not', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the object was created', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the object was last updated', null=True, verbose_name='Updated At')),
                ('tagline', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tagline')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/logo', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/favicon', verbose_name='Favicon')),
                ('primary_color', models.CharField(blank=True, max_length=255, null=True, verbose_name='Primary Color')),
                ('secondary_color', models.CharField(blank=True, max_length=255, null=True, verbose_name='Secondary Color')),
                ('font_family', models.CharField(blank=True, max_length=255, null=True, verbose_name='Font Family')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Branding',
                'verbose_name_plural': 'Brandings',
                'db_table': 'branding',
            },
        ),
    ]
